### PR TITLE
readme: fix code format

### PR DESCRIPTION
**Pull request by jimen0**
This PR formats `README.md` code snippets.

Kind regards 💯

### CODE REVIEW

**Comment by jimen0** [comment]
cc @cr0hn

**Comment by alsanchez** [comment]
@jimen0: could you rebase with master please? We happened to be updating the README file at the time of your pull request.

**Comment by jimen0** [comment]
Please, take another look @alsanchez

**Comment by alsanchez** [comment]
Thank you!

**Pull request merged**
